### ISSUE TITLE
HTTP Error 405

### ISSUE THREAD

**Issue by cklimbac** [jirkapinkas/sitemonitoring-production#1]
Hi, i get HTTP Error code when checking site: http://www.amazon.com/
Can you help me please?

**Comment by jirkapinkas** [comment]
First of all, don't check somebody else's website if you don't have to (for example in broken links functionality it is valid usecase, but otherwise don't do it).

Currently when you don't check for some condition (like "&lt;/html&gt;") on the page, the application will send HTTP HEAD request (also broken links functionality sends HTTP HEAD request). And amazon.com returns for HTTP HEAD request status code 405. 

I will make broken links functionality more intelligent, so it will try GET request as well, but I won't change basic check functionality (because you can simply call GET request when you add some condition.

**Comment by cklimbac** [comment]
Thanks a lot for fast reply. I wanted to test if your (by the way great piece of software) is able to monitor content changes on a webpage. That was the reason i started with amazon, because i wanted to watch out for changes on an amazon article. As this was not working properly, i tested the root page which is amazon.com. Just to tell you why was watching amazon.com.

**Comment by araz1367** [comment]
hi can you help me to write the update method for blog for Java-blog -aggregator

**Comment by jirkapinkas** [comment]
it's already done in the latest branch of the original project:

https://github.com/jirkapinkas/java-blog-aggregator/tree/latest

and also in the new project, which is based on Spring Boot and I replaced
JSP with Thymeleaf:

https://github.com/jirkapinkas/java-blog-aggregator-boot



JP

2016-02-08 16:01 GMT+01:00 araz1367 <notifications@github.com>:

**Comment by araz1367** [comment]
tankeyou very much your tutorial is very good and many help me.
sry my english is very bad
